### ISSUE TITLE
In which case will get null?

### ISSUE THREAD

**Issue by aiyuzhou** [greengerong/rebirth-http#10]
I saw the comment will get null if TypeScript Interface isn't visible in runtime, but why TypeScript Interface isn't visible? it's werid, I build an ionic app in dev, it works well, but when I build app with a -prod flag it is broken, then get null, so I want to know in which case TypeScript Interface isn't visible?

**Comment by wzhudev** [comment]
Hi. @aiyuzhou

TypeScript would compile to JavaScript before runtime. So at runtime, it's actually JavaScript and as we all known JavaScript is weak-type language.
