### ISSUE TITLE
Fails to work in production mode

### ISSUE THREAD

**Issue by alfie-far** [greengerong/rebirth-http#11]
Hi ...
First of all, Thanks! I really appreciate the time and effort you've put into this module.

While testing your module I realized when using it in production mode the library fails
to work properly.
The error message I am getting is: 

> invalid assignment to const `n'

This happens when I make a HTTP request and the app stops working afterwards.
I tested this in latest version of angular

**Comment by alfie-far** [comment]
I am sorry the error message didn't have anything to do with your module. It was something else.

**Comment by amin-RFarzin** [comment]
I am sorry the error message didn't have anything to do with your module. It was something else.
