### ISSUE TITLE
About the rebirthHttpProvider·s  action scope

### ISSUE THREAD

**Issue by yunClouds** [greengerong/rebirth-http#13]
hello @greengerong  
   狼主你好，发现有一个服务作用域的问题：根据您的api在app.component中进行Global interceptors，当我的service是在AppModule中进行provide，或者在其他子模块块中provide，且要将该子模块import到AppModule的话，那没问题；但如果我是用的懒加载方式创建路由，并且有部分service在懒加载模块中声明，那在这里面的service将无法被Rebirth-http包装。
![image](https://user-images.githubusercontent.com/26613310/37967801-005ee636-31ff-11e8-9270-5c463b6a4f1d.png)

    请问这个问题能怎么解决，或者不知道是我还有什么地方没配置好？谢谢

**Comment by greengerong** [comment]
这是由于ng的创建机制导致的。 你吧rebirth-http申明在app module那么在创建这个实例的时候，肯定没有你懒加载的服务存在。

**Comment by yunClouds** [comment]
@greengerong      
     是的，懒加载中的服务是在模块被加载时才初始化，我尝试过在子模块加载初始化时用可观察者模式的服务通知app-component重新执行其中rebirth-http 的Global interceptors相关方法（是想这样能不能达到让rebirth-http的rebirthHttpProvider把子模块中的服务也加入管理），可能我理解上还有出入，没有达到预想的效果。
     当然现在这样在appmodule中全局provide所有服务也是可以的，就是想说不知道是否有办法能做到，子模块的服务在子模块中provides也可以让rebirth-http监管到？那样“模块化”就更彻底。

Thanks!

**Comment by greengerong** [comment]
拦截器是全局执行的，lazyload模块没加载情况下，也会执行。如果你是在某些模块加载了才执行某些拦截器，那么你需要自己装载和卸载拦截器。那么if以及利用injector懒注入来装载和卸载。
