### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by wfsovereign** [greengerong/rebirth-http#2]
rebirth-http.ts文件第114行：

```javascript
         if (type.indexOf('json') !== -1) {
```

当header中拿不到content type的时候这里会报错，建议改成：

```javascript
           if (type && type.indexOf('json') !== -1) {
```

**Comment by greengerong** [comment]
Thanks. Will fix it soon.

**Comment by greengerong** [comment]
Fixed [https://github.com/greengerong/rebirth-http/commit/d634b3573ff3d53d5d2ff83b020cccda31651101](https://github.com/greengerong/rebirth-http/commit/d634b3573ff3d53d5d2ff83b020cccda31651101)

rebirth-http version 0.0.7 [https://www.npmjs.com/package/rebirth-http](https://www.npmjs.com/package/rebirth-http)
