### ISSUE TITLE
Why not support patch method?

### ISSUE THREAD

**Issue by hejiaji** [greengerong/rebirth-http#3]
I don't see patch method in api, is there any reason behind it?

**Comment by greengerong** [comment]
we can add this function when you should use patch method.

**Comment by greengerong** [comment]
Please check commit [https://github.com/greengerong/rebirth-http/commit/f589c4a3e2df960b45b8b902df9f3a079af94bed](https://github.com/greengerong/rebirth-http/commit/f589c4a3e2df960b45b8b902df9f3a079af94bed)

rebirth-http version 0.0.7 [https://www.npmjs.com/package/rebirth-http](https://www.npmjs.com/package/rebirth-http)

**Comment by hejiaji** [comment]
Thanks!, cool, will give it a try
