### ISSUE TITLE
Query don't support empty character string

### ISSUE THREAD

**Issue by wfsovereign** [greengerong/rebirth-http#4]
In my work, I find use @Query parameter send a empty character string but don't send this field actually. Through review source code,  I find this code ,

```javascript 
       .filter(p => args[p.parameterIndex]) // filter out optional parameters
```
[there](https://github.com/greengerong/rebirth-http/blob/master/src/rebirth-http.ts#L279),
I think url query parameter should support empty character string, so it's can modify to 

```javascript 
       .filter(p => args[p.parameterIndex] || args[p.parameterIndex] === '') // filter out optional parameters
```

what do you think of that? @greengerong ☺️

**Comment by greengerong** [comment]
changed to 

      pQuery.filter(p => !isUndefined(args[p.parameterIndex]))

And

     $ npm publish
     + rebirth-http@0.0.9

**Comment by wfsovereign** [comment]
cool! so fast!!

**Comment by greengerong** [comment]
@wfsovereign  It works for you?
