### ISSUE TITLE
怎么添加 withCredentials？

### ISSUE THREAD

**Issue by consilient-hengtian** [greengerong/rebirth-http#7]

**Comment by greengerong** [comment]
可以选择在拦截器中添加 withCredentials，或者是class级别 @DefaultHeaders(headers: Object)、方法级别@Header(key: string)添加。


     @Cacheable({ pool: 'articles' })
     @GET('article')
     fetchArticles(@Query('pageIndex') pageIndex = 1,
                @Query('pageSize') pageSize = 10,
                @Header('withCredentials')  withCredentials: boolean,
                @Query('keyword') keyword?: string): Observable<SearchResult<Article>> {
           return null;
      }

或者：

    @Injectable()
    @DefaultHeaders({
           withCredentials: true
     })
     export class OnlineArticleService extends RebirthHttp implements IArticleService {

      }

![image](https://user-images.githubusercontent.com/2569893/27318041-b876e0b8-55bc-11e7-9948-7574e125c0d4.png)
