### ISSUE TITLE
@Query 装饰器声明的对象有问题

### ISSUE THREAD

**Issue by lynings** [greengerong/rebirth-http#9]
rebirth-http 版本 0.1.3

# 错误代码位置
[错误代码位置](https://github.com/greengerong/rebirth-http/blob/e792c8796206495936fc439d72611630d714ae96/src/rebirth-http.ts#L298)

# 问题描述
当使用 @GET 和 @Query 配合使用的时候，@Query 声明的对象会出问题！比如下面的伪代码，最后请求的地址是 https://ip:port/page?end=2017-01-01，start 参数没有被整合到 url 中，进 debug 发现是 [错误代码位置](https://github.com/greengerong/rebirth-http/blob/e792c8796206495936fc439d72611630d714ae96/src/rebirth-http.ts#L298) 的 result 每次都被 ps.set(k, value[k]) 覆盖，导致遍历的时候，result 只会保存最后一次遍历的属性

# 伪代码
``` typescript
export class QueryPageRequest {
    public start: string;
    public end: string;
}

service:

@GET('/page')
queryByPage(@Query('req') req: QueryPageRequest) :Observable<any> {
    return null;
}
```

**Comment by greengerong** [comment]
fix in version 0.1.4
